"""creating relationships

Revision ID: 175351c4e9b2
Revises: 72e54056303d
Create Date: 2024-01-11 15:24:46.319522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175351c4e9b2'
down_revision = '72e54056303d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
