"""creating tables

Revision ID: 6f2b85305104
Revises: 845ccf2d865c
Create Date: 2024-01-11 10:29:56.712756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2b85305104'
down_revision = '845ccf2d865c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
