"""creating instaces on tables

Revision ID: b4b0999f14aa
Revises: 6f2b85305104
Create Date: 2024-01-11 11:57:24.294810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b0999f14aa'
down_revision = '6f2b85305104'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('album_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'songs', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'songs', 'albums', ['album_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'album_id')
    op.drop_column('songs', 'artist_id')
    # ### end Alembic commands ###
